export const ADD_WALLET = "ADD_WALLET";
export const CHANGE_ACTIVE_WALLET = "CHANGE_ACTIVE_WALLET";
export const ADD_RECENT_STABLECOIN = "ADD_RECENT_STABLECOIN";
export const ADD_EXCHANGE = "ADD_EXCHANGE";
